language: java

jdk:
  - oraclejdk8

install: true

script:
  - mvn clean install -Dbuild.number=${env.TRAVIS_BUILD_NUMBER} -Dbranch.name=$TRAVIS_BRANCH -DskipTests=true -Dmaven.javadoc.skip=true -B -V
